### ISSUE TITLE
PPF not showing properly with FrameSort addon

### ISSUE THREAD

**Issue by burnep** [cleanlock/Partyframe-Pets-Fix#4]
FrameSort: https://www.curseforge.com/wow/addons/framesort

I'm not sure which addon (framesort or partypets) is causing this but using FrameSort's experimental mode causes frames to look like this

![pets](https://user-images.githubusercontent.com/40314230/219993310-369930ec-1d98-46a2-b3d6-2f3774e3e048.png)

Will also post to that addon's github, but since it's not a problem for SortGroup, thought you should know.

Cheers

**Comment by burnep** [comment]
A partial fix would be to uncap the Y coordinates you can set instead of 100

**Comment by Verubato** [comment]
I'm the developer of [FrameSort ](https://github.com/Verubato/frame-sort) and see a few options for how we could remedy this:

**1. Change the PPF anchor.**

Instead of anchoring to the last group member:

[Core.lua](https://github.com/cleanlock/PartyPets-Fix/blob/master/Core.lua)

`SetPoint("LEFT", _G["CompactPartyFrameMember" .. GetNumGroupMembers()], "LEFT", PPF_DB.positionx, PPF_DB.positiony)`, 

Anchor to the bottom most visible child of CompactPartyFrame, e.g. something like:

```
local frames = { CompactPartyFrame:GetChildren() }
local anchor = nil

for i, frame in ipairs(frames) do
    if frame.unit and frame:IsVisible() and (not anchor or frame:GetBottom() < anchor:GetBottom()) then
        anchor = frame
    end
end

print(anchor.unit)
```

**2. FrameSort/PPF API**

Some public functions that FrameSort/PPF can use for positioning.
e.g. `PPF:Refresh(anchor)` or `FrameSort:GetBottomAnchor()`

This could be useful as FrameSort changes sorting depending on the player's current instance type (i.e. arena, bg, raid, dungeon)

**3. FrameSort repositions PPF frames.**

Not ideal for FrameSort to do this, but listing it as an option nonetheless.

--------------

What would be your preferred approach @cleanlock?

**Comment by muleyo** [comment]
Hi,

I could change the PPF anchor. Your solution seems to be very simple, so I don't see any reason to not change the code. :)

Give me 1-2 days as I'm kinda busy at the moment. Thanks for your input!

**Comment by Akiat** [comment]
Hi there!
First of all, thanks for your work 👍
Just to say that I'm super interested to have this fix :)
Thanks in advance!
